In [78]:
%matplotlib inline
from scipy import ndimage
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import cPickle

In [83]:
# http://www.msri.org/people/members/eranb/figure_ground.tar.gz
HORSE_PATH='weizmann_horse_db/figure_ground/'
OUT_PATH='weizmann/'

In [85]:
for f in next(os.walk(HORSE_PATH))[2]:
    img = Image.open(HORSE_PATH+f)
    img = img.resize((28, 28), Image.ANTIALIAS)
    img.save(OUT_PATH+f)

In [94]:
dataset = np.zeros((328,28,28,1))
for i in range(1, 329):
    img = ndimage.imread(OUT_PATH+'horse%03d.jpg'%i)
    img = img.reshape(28,28,1)
    dataset[i-1] = img/255.0
print dataset.shape
print np.mean(dataset)
cPickle.dump(dataset, open( "weizmann.pkl", "wb" ) )


(328, 28, 28, 1)
0.256268544003


In [95]:
print dataset[0]

[[[ 0.00784314]
  [ 0.        ]
  [ 0.05490196]
  [ 0.        ]
  [ 0.00392157]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.02352941]
  [ 0.        ]
  [ 0.        ]
  [ 0.03529412]
  [ 0.        ]
  [ 0.        ]
  [ 0.00784314]
  [ 0.00784314]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.00392157]
  [ 0.        ]
  [ 0.03921569]
  [ 0.        ]
  [ 0.01176471]
  [ 0.        ]
  [ 0.01176471]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.00784314]
  [ 0.        ]
  [ 0.        ]
  [ 0.02352941]
  [ 0.05490196]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]]

 [[ 0.00784314]
  [ 0.        ]
  [ 0.00392157]
  [ 0.01176471]
  [ 0.01176471]
  [ 0.        ]
  [ 